// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_country_area_ from "./routes/[country]/[area].tsx";
import * as $_country_index from "./routes/[country]/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_v2_hass from "./routes/api/v2/hass.tsx";
import * as $api_v2_spot from "./routes/api/v2/spot.tsx";
import * as $custom from "./routes/custom.tsx";
import * as $help from "./routes/help.tsx";
import * as $homeassistant from "./routes/homeassistant.tsx";
import * as $index from "./routes/index.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $AreaIsland from "./islands/AreaIsland.tsx";
import * as $CountryIsland from "./islands/CountryIsland.tsx";
import * as $CustomIsland from "./islands/CustomIsland.tsx";
import * as $HassIsland from "./islands/HassIsland.tsx";
import * as $HelpIsland from "./islands/HelpIsland.tsx";
import * as $IndexIsland from "./islands/IndexIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[country]/[area].tsx": $_country_area_,
    "./routes/[country]/index.tsx": $_country_index,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/v2/hass.tsx": $api_v2_hass,
    "./routes/api/v2/spot.tsx": $api_v2_spot,
    "./routes/custom.tsx": $custom,
    "./routes/help.tsx": $help,
    "./routes/homeassistant.tsx": $homeassistant,
    "./routes/index.tsx": $index,
    "./routes/sitemap.xml.ts": $sitemap_xml,
  },
  islands: {
    "./islands/AreaIsland.tsx": $AreaIsland,
    "./islands/CountryIsland.tsx": $CountryIsland,
    "./islands/CustomIsland.tsx": $CustomIsland,
    "./islands/HassIsland.tsx": $HassIsland,
    "./islands/HelpIsland.tsx": $HelpIsland,
    "./islands/IndexIsland.tsx": $IndexIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
