// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[country]/[area].tsx";
import * as $1 from "./routes/[country]/index.tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_500.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/api/v2/hass.tsx";
import * as $6 from "./routes/api/v2/spot.tsx";
import * as $7 from "./routes/custom.tsx";
import * as $8 from "./routes/help.tsx";
import * as $9 from "./routes/homeassistant.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/sitemap.xml.ts";
import * as $$0 from "./islands/CustomIsland.tsx";
import * as $$1 from "./islands/ElomradeIsland.tsx";
import * as $$2 from "./islands/HassIsland.tsx";
import * as $$3 from "./islands/HelpIsland.tsx";
import * as $$4 from "./islands/IndexIsland.tsx";

const manifest = {
  routes: {
    "./routes/[country]/[area].tsx": $0,
    "./routes/[country]/index.tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_500.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/api/v2/hass.tsx": $5,
    "./routes/api/v2/spot.tsx": $6,
    "./routes/custom.tsx": $7,
    "./routes/help.tsx": $8,
    "./routes/homeassistant.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/sitemap.xml.ts": $11,
  },
  islands: {
    "./islands/CustomIsland.tsx": $$0,
    "./islands/ElomradeIsland.tsx": $$1,
    "./islands/HassIsland.tsx": $$2,
    "./islands/HelpIsland.tsx": $$3,
    "./islands/IndexIsland.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
