name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.29.1, "v1.x"]
        timezone: ["Europe/Stockholm"]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Test Deno Formatting
        run: deno fmt --check
      - name: Test Deno Linting
        run: deno lint
      - name: Test Deno Types
        run: deno check main.ts
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: ${{ matrix.timezone }}
      - name: Test Deno Module
        run: deno test